import { About } from "@/components/About";
import { ContactBanner } from "@/components/ContactBanner";
import { NavBar } from "@/components/NavBar";
import { Projects } from "@/components/Projects";
import Head from "next/head";
import { InitialHome } from "../components/InitialHome";

export default function Home() {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@600&family=Poppins:wght@700&display=swap" rel="stylesheet"/>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Portfolio.ico" />
      </Head>
      <main>
        <NavBar />
        <InitialHome />
        <About />
        <Projects />
        <ContactBanner />
      </main>
    </>
  );
}
